# Generated by Django 3.2.4 on 2021-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('home', 'Home_stuff'), ('work', 'Work_stuff'), ('leisure', 'Leisure_stuff')], max_length=20),
        ),
    ]
